const COMMUNITY_RESOURCES = [
  {
    categoryName: "Layanan & Tools",
    iconSvg: `<rect x="2" y="3" width="20" height="14" rx="2" /><line x1="8" y1="21" x2="16" y2="21" /><line x1="12" y1="17" x2="12" y2="21" />`,
    items: [
      {
        owner: "YOGIKID",
        title: "ArusKas",
        url: "https://aruskas.app",
        tag: "Personal & Business Finance",
        tagClass: "",
      },
      {
        owner: "Nauval",
        title: "VPS & NOKOS Murah",
        url: "https://t.me/Ordernatkanada2bot",
        tag: "Telegram Bot",
        tagClass: "",
      },
      {
        owner: "Nauval",
        title: "Layanan Perantara",
        url: "https://mustikapayment.com",
        tag: "Intermediary Layer",
        tagClass: "",
      },
      {
        owner: "Arvan",
        title: "Beli Panel",
        url: "https://t.me/tokopteroBot",
        tag: "Telegram Bot",
        tagClass: "",
      },
    ],
  },
  {
    categoryName: "CDN",
    iconSvg: `<polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />`,
    items: [
      {
        owner: "Shaq",
        title: "Cloud Yardansh",
        url: "https://cloud.yardansh.com",
        tag: "CDN",
        tagClass: "",
      },
      {
        owner: "Fgsi",
        title: "CDN Fgsi",
        url: "https://cdn.fgsi.dpdns.org",
        tag: "CDN",
        tagClass: "",
      },
      {
        owner: "elkhaff",
        title: "Stash",
        url: "https://stash.cc.cd",
        tag: "CDN",
        tagClass: "",
      },
    ],
  },
  {
    categoryName: "Public API",
    iconSvg: `<path d="M18 20V10" /><path d="M12 20V4" /><path d="M6 20v-6" />`,
    items: [
      {
        owner: "Elrayy",
        title: "Nexray API",
        url: "https://api.nexray.web.id",
        tag: "No API Key",
        tagClass: "tag-free",
      },
      {
        owner: "Febry",
        title: "Azbry API",
        url: "https://api.azbry.com",
        tag: "Public",
        tagClass: "tag-free",
      },
      {
        owner: "Alex",
        title: "Paxsenix API",
        url: "https://api.paxsenix.org",
        tag: "Public",
        tagClass: "tag-free",
      },
      {
        owner: "Najwa",
        title: "Anabot",
        url: "https://anabot.my.id",
        tag: "Public",
        tagClass: "tag-free",
      },
      {
        owner: "Fgsi",
        title: "Fgsi API",
        url: "https://fgsi.dpdns.org",
        tag: "API Key",
        tagClass: "tag-key",
      },
      {
        owner: "Kayz",
        title: "Kayz API",
        url: "https://studio-claude.biz.id",
        tag: "API Key",
        tagClass: "tag-key",
      },
      {
        owner: "Syaii Astro",
        title: "Covenant API",
        url: "https://covenant.sbs",
        tag: "API Key",
        tagClass: "tag-key",
      },
      {
        owner: "Kadokun",
        title: "Nexray API",
        url: "https://api.nexray.eu.cc",
        tag: "API Key",
        tagClass: "tag-key",
      },
      {
        owner: "Nathan",
        title: "Astralune API",
        url: "https://myapi.astralune.cv",
        tag: "Public",
        tagClass: "tag-free",
      },
      {
        owner: "Rafli",
        title: "Neosoft API",
        url: "https://api.neosoft.best",
        tag: "Public",
        tagClass: "tag-free",
      },
      {
        owner: "Nauval",
        title: "YT-DLP Python",
        url: "https://ytdlpyton.nvlgroup.my.id/",
        tag: "Downloader",
        tagClass: "",
      },
      {
        owner: "Fgsi",
        title: "YT Downloader",
        url: "https://yt.fgsi.my.id",
        tag: "Downloader",
        tagClass: "",
      },
    ],
  },
  {
    categoryName: "Bot API",
    iconSvg: `<rect x="3" y="11" width="18" height="11" rx="2" ry="2" /><path d="M7 11V7a5 5 0 0110 0v4" />`,
    items: [
      {
        owner: "Ryan",
        title: "My4Tube",
        url: "https://my4tube.my.id",
        tag: "Maintenance",
        tagClass: "tag-maintenance",
        isDim: true,
      },
      {
        owner: "Ryan",
        title: "FluffCDN",
        url: "https://fluffcdn.my.id",
        tag: "CDN",
        tagClass: "",
      },
      {
        owner: "Ryan",
        title: "Lunarin",
        url: "https://lunarin.sbs",
        tag: "API Key",
        tagClass: "tag-key",
      },
    ],
  },
  {
    categoryName: "Awesome Web",
    iconSvg: `<circle cx="12" cy="12" r="10" /><line x1="2" y1="12" x2="22" y2="12" /><path d="M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z" />`,
    items: [
      {
        owner: "RifkyShre",
        title: "Codespace",
        url: "https://code.rifkyshre.biz.id/",
        tag: "Web",
        tagClass: "",
      },
      {
        owner: "Shaq",
        title: "Codespace",
        url: "https://codespace.yardansh.com",
        tag: "Web",
        tagClass: "",
      },
      {
        owner: "Ren",
        title: "Space Code",
        url: "https://space-code-xyz.vercel.app",
        tag: "Web",
        tagClass: "",
      },
      {
        owner: "wolep",
        title: "Wolep",
        url: "https://wolep.surge.sh/",
        tag: "Web",
        tagClass: "",
      },
      {
        owner: "wolep",
        title: "Wolep Dev",
        url: "https://wolep.dev/",
        tag: "Web",
        tagClass: "",
      },
    ],
  },
  {
    categoryName: "Scripts & Snippets",
    iconSvg: `<polyline points="16 18 22 12 16 6" /><polyline points="8 6 2 12 8 18" />`,
    items: [
      {
        owner: "wolep",
        title: "WolfyFlutter Pastes",
        url: "https://pastebin.com/u/wolfyflutter",
        tag: "Pastebin",
        tagClass: "",
      },
      {
        owner: "siputzx",
        title: "Siputzx Code",
        url: "https://code.siputzx.my.id",
        tag: "Code",
        tagClass: "",
      },
      {
        owner: "Fgsi",
        title: "Pastebin List",
        url: "https://fgsi.dpdns.org/pastebin/list",
        tag: "Pastebin List",
        tagClass: "",
      },
    ],
  },
];

const GITHUB_PROJECTS = [
  {
    url: "https://github.com/WolfyFlutter/angelina-bot",
    repo: "WolfyFlutter/angelina-bot",
    title: "Angelina Bot",
    desc: "Bot WA utama komunitas Angelina Empire. Actively developed.",
    lang: "JavaScript",
    langClass: "pc-lang-js",
    author: "WolfyFlutter",
    badge: "Active Dev",
    isFeatured: true,
  },
  {
    url: "https://github.com/vandebry10-star/wesker-bot",
    repo: "vandebry10-star/wesker-bot",
    title: "Wesker Bot",
    desc: "WhatsApp bot berbasis JavaScript.",
    lang: "JavaScript",
    langClass: "pc-lang-js",
    author: "vandebry10-star",
    badge: null,
    isFeatured: false,
  },
  {
    url: "https://github.com/AgusXzz/ChiiMD",
    repo: "AgusXzz/ChiiMD",
    title: "ChiiBot",
    desc: "WhatsApp bot berbasis JavaScript.",
    lang: "JavaScript",
    langClass: "pc-lang-js",
    author: "AgusXzz",
    badge: null,
    isFeatured: false,
  },
  {
    url: "https://github.com/kadomatcha/Rika",
    repo: "kadomatcha/Rika",
    title: "Rika",
    desc: "WhatsApp bot berbasis JavaScript.",
    lang: "JavaScript",
    langClass: "pc-lang-js",
    author: "kadomatcha",
    badge: null,
    isFeatured: false,
  },
  {
    url: "https://github.com/BangsulBotz/BANGSULBOTZ_V2_PUBLIK",
    repo: "BangsulBotz/BANGSULBOTZ_V2_PUBLIK",
    title: "Bangsul Bot V2",
    desc: "WhatsApp bot publik berbasis JavaScript.",
    lang: "JavaScript",
    langClass: "pc-lang-js",
    author: "BangsulBotz",
    badge: null,
    isFeatured: false,
  },
  {
    url: "https://github.com/siputzx/sptzxgo",
    repo: "siputzx/sptzxgo",
    title: "Arvan (sptzxgo)",
    desc: "WhatsApp bot berbasis Go — the fast one.",
    lang: "Go",
    langClass: "pc-lang-go",
    author: "siputzx",
    badge: null,
    isFeatured: false,
  },
];
